name: Deploy to GitHub Pages

on:
  push:
    branches:
      - Latest_ver

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --prefix ./frontend

    - name: Build website
      run: npm run build --prefix ./frontend

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/frontend
        publish_branch: gh-pages
